# Generated by Django 5.0.1 on 2024-01-18 18:03

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z]*$", message="Only latin letters are allowed."
                            )
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z]+(?: [a-zA-Z]+)*$",
                                message="Only latin letters and single spaces are allowed, no trailing spaces.",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetOfExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "n_repetitions",
                    models.PositiveSmallIntegerField(
                        verbose_name="Number of repetitions"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, help_text="Weight in kilograms", max_digits=6
                    ),
                ),
                (
                    "volume",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("n_repetitions"), "*", models.F("weight")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=1, max_digits=10
                        ),
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"), name="unique_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("code", "name"), name="unique_exercise"
            ),
        ),
        migrations.AddField(
            model_name="setofexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workouts.exercise"
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="setofexercise",
            name="workout",
            field=models.ForeignKey(
                help_text="When was this set performed?",
                on_delete=django.db.models.deletion.CASCADE,
                to="workouts.workout",
            ),
        ),
        migrations.AddConstraint(
            model_name="workout",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_user_date_workout"
            ),
        ),
    ]
