# Generated by Django 4.2.7 on 2023-11-26 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_unique_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='code',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Only latin letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+(?: [a-zA-Z]+)*$', message='Only latin letters and single spaces are allowed, no trailing spaces.')]),
        ),
    ]
