# Generated by Django 5.0 on 2023-12-07 00:36

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercise_code_alter_exercise_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setofexercise',
            name='volume',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('n_repetitions'), '*', models.F('weight')), output_field=models.DecimalField(decimal_places=1, max_digits=10)),
        ),
        migrations.AlterField(
            model_name='setofexercise',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='Weight in kilograms', max_digits=6),
        ),
    ]
