# Generated by Django 4.2.7 on 2023-11-19 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_exercise_code_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='code',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', message='Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', message='Only letters and spaces are allowed.')]),
        ),
    ]
