# Generated by Django 4.2.7 on 2023-11-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_exercise_code_alter_exercise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetOfExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_repetitions', models.PositiveSmallIntegerField(verbose_name='Number of repetitions')),
                ('weight', models.DecimalField(decimal_places=1, help_text='Weight in kilograms', max_digits=5)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
            ],
        ),
    ]
